- name: Install Kali tools
  hosts: kali
  become: yes
  tasks:
    - name: Update apt and install gnupg
      apt:
        update_cache: yes
        name: gnupg
        state: present

    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Kali archive signing key
      get_url:
        url: https://archive.kali.org/archive-key.asc
        dest: /etc/apt/keyrings/kali.asc

    - name: Convert signing key to GPG format
      command: >
        gpg --dearmor -o /etc/apt/keyrings/kali.gpg /etc/apt/keyrings/kali.asc
      args:
        creates: /etc/apt/keyrings/kali.gpg

    - name: Add Kali repository with signed-by option
      copy:
        dest: /etc/apt/sources.list.d/kali.list
        content: |
          deb [signed-by=/etc/apt/keyrings/kali.gpg] http://kali.download/kali kali-rolling main contrib non-free

    - name: Update apt cache after adding repo
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Kali tools
      apt:
        name:
          - nmap
          - hping3
          - hydra
        state: present
